import {DatabaseSync} from 'node:sqlite';
import {createHash,randomBytes} from 'node:crypto';
import {due,settings,validatePlan} from '../public/shared/domain.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
export class Ledger{
 constructor(file){this.db=new DatabaseSync(file);this.db.exec(`PRAGMA journal_mode=WAL;PRAGMA synchronous=FULL;PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS public_events(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,payload TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,token_hash TEXT NOT NULL,subscription TEXT NOT NULL,preferences TEXT NOT NULL,plans TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS outbox(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,device TEXT NOT NULL,plan_id TEXT,payload TEXT NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_at INTEGER NOT NULL,last_error TEXT);
 CREATE TABLE IF NOT EXISTS acknowledgements(id TEXT PRIMARY KEY,device TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);`)}
 transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const r=fn();this.db.exec('COMMIT');return r}catch(e){this.db.exec('ROLLBACK');throw e}}
 event(id,payload){this.db.prepare('INSERT OR IGNORE INTO public_events(id,payload,at) VALUES(?,?,?)').run(id,JSON.stringify(payload),new Date().toISOString())}
 publicEvents(cursor=0){return this.db.prepare('SELECT seq,payload FROM public_events WHERE seq>? ORDER BY seq LIMIT 500').all(cursor).map(r=>({...JSON.parse(r.payload),seq:r.seq}))}
 get(key){const r=this.db.prepare('SELECT value FROM meta WHERE key=?').get(key);return r?JSON.parse(r.value):null}
 set(key,value){this.db.prepare('INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,JSON.stringify(value))}
 register(sub,prefs,plans){const endpointHash=hash(sub.endpoint),token=randomBytes(32).toString('base64url'),id=endpointHash.slice(0,40);prefs=settings(prefs);plans.forEach(validatePlan);const old=this.db.prepare('SELECT * FROM devices WHERE id=?').get(id);this.transaction(()=>{if(old){this.db.prepare('UPDATE devices SET token_hash=?,subscription=?,active=1 WHERE id=?').run(hash(token),JSON.stringify(sub),id);this.update(old,prefs,plans)}else this.db.prepare('INSERT INTO devices(id,token_hash,subscription,preferences,plans,active) VALUES(?,?,?,?,?,1)').run(id,hash(token),JSON.stringify(sub),JSON.stringify(prefs),JSON.stringify(plans))});return {id,token}}
 authorize(token){if(typeof token!=='string'||token.length>100)return null;return this.db.prepare('SELECT * FROM devices WHERE token_hash=?').get(hash(token))||null}
 update(device,prefs,plans){prefs=settings(prefs);if(!Array.isArray(plans)||plans.length>1000)throw Error('Invalid plans');plans.forEach(validatePlan);const previous=new Map(JSON.parse(device.plans).map(p=>[p.id,p]));const merged=plans.map(p=>{const old=previous.get(p.id);if(!old)return p;return {...p,calendarSeen:[...new Set([...(old.calendarSeen||[]),...(p.calendarSeen||[])])],lastNoticeAt:[old.lastNoticeAt,p.lastNoticeAt].filter(Boolean).sort().at(-1)||null,arrivalSeen:old.arrivalSeen||p.arrivalSeen||null}});this.db.prepare('UPDATE devices SET preferences=?,plans=? WHERE id=?').run(JSON.stringify(prefs),JSON.stringify(merged),device.id)}
 queue(device,notice,now=Date.now()){this.db.prepare("INSERT OR IGNORE INTO outbox(id,device,plan_id,payload,status,next_at) VALUES(?,?,?,?,'queued',?)").run(notice.id,device,notice.planId||null,JSON.stringify(notice),now)}
 schedule(now=Date.now()){this.transaction(()=>{for(const d of this.db.prepare('SELECT * FROM devices WHERE active=1').all()){const prefs=JSON.parse(d.preferences),plans=JSON.parse(d.plans);const next=plans.map(p=>{const r=due(p,prefs,now);if(r.notice){this.db.prepare("UPDATE outbox SET status='superseded' WHERE device=? AND plan_id=? AND status IN ('queued','retry')").run(d.id,p.id);this.queue(d.id,r.notice,now)}return r.plan});this.db.prepare('UPDATE devices SET plans=? WHERE id=?').run(JSON.stringify(next),d.id);const valid=new Set(next.filter(p=>!p.cancelled).map(p=>p.id));for(const r of this.db.prepare("SELECT seq,plan_id FROM outbox WHERE device=? AND status IN ('queued','retry') AND plan_id IS NOT NULL").all(d.id))if(!valid.has(r.plan_id))this.db.prepare("UPDATE outbox SET status='cancelled' WHERE seq=?").run(r.seq)}})}
 jobs(now=Date.now()){return this.db.prepare("SELECT o.*,d.subscription FROM outbox o JOIN devices d ON d.id=o.device WHERE d.active=1 AND o.status IN ('queued','retry') AND next_at<=? ORDER BY seq LIMIT 20").all(now)}
 success(row){this.db.prepare("UPDATE outbox SET status='transport-accepted',attempts=attempts+1,last_error=NULL WHERE seq=?").run(row.seq)}
 failure(row,error,now=Date.now()){if([404,410].includes(error.status)){this.db.prepare('UPDATE devices SET active=0 WHERE id=?').run(row.device);this.db.prepare("UPDATE outbox SET status='subscription-expired',attempts=attempts+1,last_error=? WHERE seq=?").run(error.message,row.seq);return}const attempts=row.attempts+1;this.db.prepare('UPDATE outbox SET status=?,attempts=?,next_at=?,last_error=? WHERE seq=?').run(attempts>=8?'failed-retained':'retry',attempts,now+Math.min(3600000,30000*2**row.attempts),String(error.message).slice(0,150),row.seq)}
 inbox(device,cursor=0){return this.db.prepare('SELECT seq,payload,status FROM outbox WHERE device=? AND seq>? ORDER BY seq LIMIT 500').all(device,cursor).map(r=>({seq:r.seq,notice:JSON.parse(r.payload),transport:r.status}))}
 ack(device,id){this.db.prepare('INSERT OR IGNORE INTO acknowledgements(id,device,at) SELECT id,device,? FROM outbox WHERE id=? AND device=?').run(new Date().toISOString(),id,device)}
 close(){this.db.close()}
}
