import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium,ownedProcesses,processes,waitFor} from './browser-helper.mjs';
const prior=JSON.parse(await fs.readFile('output/qa-report.json','utf8'));
const base=process.env.RADAR_QA_URL||'http://127.0.0.1:5376/codex/';
const report={at:new Date().toISOString(),url:base,physicalDevice:false,checks:[],errors:[]};
let context,owned=[],originalRequests;
async function open(offline=false){context=await chromium.launchPersistentContext(prior.profile,{channel:'chrome',headless:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true});owned=ownedProcesses(prior.profile);await context.setOffline(offline);const page=context.pages()[0];page.on('pageerror',e=>report.errors.push(e.message));return page}
async function close(){if(context)await context.close();const alive=processes().filter(p=>owned.some(x=>x.pid===p.ProcessId&&x.created===p.CreationDate));assert.equal(alive.length,0);context=null;report.cleanup={remaining:[]}}
async function values(page){return page.evaluate(async()=>{const {read}=await import('./shared/storage.mjs');return read()})}
try{
 let p=await open();
 if(!process.env.RADAR_QA_URL){await p.goto('https://arisconstantinou.github.io/codex/#sources');await p.waitForSelector('.entry');const before=p.locator('.entry').filter({hasText:'0.162.0-alpha.9'}).first();await before.scrollIntoViewIfNeeded();await p.screenshot({path:'output/release-before-mobile.png'});report.before='Published previous shell: same 390x844 viewport, sources route, alpha.9 entry';}
 await p.goto(base+'#sources');await p.waitForSelector('.entry');
 const previous=await values(p);
 await p.evaluate(async()=>{const r=await navigator.serviceWorker.ready;await r.update()});
 const waiting=await waitFor(p,async()=>{const r=await navigator.serviceWorker.ready;return !!r.waiting||!!document.querySelector('[data-action=release]')});
 if(waiting){await p.evaluate(async()=>{const r=await navigator.serviceWorker.ready;r.waiting?.postMessage({type:'ACTIVATE'})});await p.waitForTimeout(800);await p.reload()}
 await p.waitForSelector('[data-action=release]');assert.equal((await values(p)).records.length,previous.records.length);report.checks.push('actual-shell-upgrade-preserves-existing-history');
 originalRequests=await p.evaluate(async()=>{const {read}=await import('./shared/storage.mjs');return await read('releaseRequests')||{blockedUntil:0,retryByTag:{}}});
 const alpha=p.locator('.entry').filter({hasText:'0.162.0-alpha.9'}).first();await alpha.scrollIntoViewIfNeeded();await p.screenshot({path:'output/release-after-mobile.png'});
 await alpha.locator('[data-action=release]').tap();
 const notes=await waitFor(p,async()=>{const {read}=await import('./shared/storage.mjs');return (await read()).items.find(x=>x.url?.endsWith('/rust-v0.162.0-alpha.9'))?.releaseNotes?.comparison?.complete&&(await read()).items.find(x=>x.url?.endsWith('/rust-v0.162.0-alpha.9')).releaseNotes},45000);
 assert.equal(notes.authored,false);assert.ok(notes.commits.length>0);assert.equal(notes.commits.length,notes.comparison.total);assert.ok((await p.textContent('#details')).includes('πραγματικά commits'));assert.equal(await p.locator('.release-changes a').count(),notes.commits.length);report.notes={tag:notes.tag,commits:notes.commits.length,status:notes.comparison.status,complete:notes.comparison.complete,body:notes.body};report.checks.push('real-GitHub-body-and-complete-actual-commit-comparison');
 for(const [name,width,height] of [['mobile',390,844],['landscape',844,390],['tablet',768,1024],['desktop',1440,1000]]){await p.setViewportSize({width,height});const metrics=await p.evaluate(()=>{const d=document.querySelector('#details'),c=document.querySelector('#close-detail'),r=c.getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth||d.scrollWidth>d.clientWidth,closeHeight:r.height,closeVisible:r.bottom<=innerHeight&&r.top>=0,minFont:Math.min(...[...d.querySelectorAll('a,small,p,summary,button')].filter(e=>e.getBoundingClientRect().height>0).map(e=>parseFloat(getComputedStyle(e).fontSize)))}});assert.equal(metrics.overflow,false,name);assert.equal(metrics.closeVisible,true,name);assert.ok(metrics.closeHeight>=44&&metrics.minFont>=12,name);await p.screenshot({path:`output/release-notes-${name}.png`});report.checks.push({name:`release-dialog-${name}`,metrics})}
 await p.setViewportSize({width:390,height:844});
 await p.route('https://api.github.com/repos/openai/codex/releases/tags/rust-v0.162.0-alpha.9',r=>r.fulfill({status:429,headers:{'Access-Control-Allow-Origin':'*','Retry-After':'900'},body:'rate limited'}));
 let requests=0;p.on('request',r=>{if(r.url().includes('/releases/tags/rust-v0.162.0-alpha.9'))requests++});
 await p.locator('[data-release-retry]').tap();await waitFor(p,async()=>{const {read}=await import('./shared/storage.mjs');return (await read('releaseRequests'))?.blockedUntil>Date.now()});await p.locator('[data-release-retry]').tap();assert.equal(requests,1);assert.deepEqual((await values(p)).items.find(x=>x.releaseNotes?.tag===notes.tag).releaseNotes,notes);report.checks.push('429-retains-full-notes-and-suppresses-repeat-fetch');
 const backup=await p.evaluate(async()=>{const {read,backup}=await import('./shared/storage.mjs');return backup(await read())});await p.evaluate(async b=>{const {restore}=await import('./shared/storage.mjs');await restore(JSON.stringify(b))},backup);assert.deepEqual((await values(p)).items.find(x=>x.releaseNotes?.tag===notes.tag).releaseNotes,notes);report.checks.push('full-release-notes-in-validated-backup-merge');
 await close();p=await open(true);await p.goto(base+'#sources');await p.waitForSelector('[data-action=release]');await p.locator('.entry').filter({hasText:'0.162.0-alpha.9'}).first().locator('[data-action=release]').tap();assert.deepEqual((await values(p)).items.find(x=>x.releaseNotes?.tag===notes.tag).releaseNotes,notes);assert.equal(await p.locator('.release-changes a').count(),notes.commits.length);const retry=await p.evaluate(async()=>{const {read}=await import('./shared/storage.mjs');return read('releaseRequests')});assert.ok(retry.blockedUntil>Date.now());await p.screenshot({path:'output/release-notes-offline-cold.png'});report.checks.push('whole-browser-cold-offline-notes-and-backoff-restored');
 await p.evaluate(async original=>{const {write}=await import('./shared/storage.mjs');await write('releaseRequests',original)},originalRequests);assert.equal(report.errors.length,0);
}catch(e){report.fatal=e.stack;process.exitCode=1}finally{try{await close()}catch(e){report.cleanupError=e.message;process.exitCode=1}await fs.writeFile(`output/release-report${process.env.RADAR_QA_URL?'-deployed':''}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))}
