import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium,waitFor,ownedProcesses,processes} from './browser-helper.mjs';
const out=path.resolve('output'),profile=path.join(out,`browser-qa-${Date.now()}`);await fs.mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),url:'http://127.0.0.1:5376/codex/',emulation:true,physicalMobile:false,checks:[],errors:[],profile};let context,owned=[];
try{context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:1440,height:940},permissions:['notifications'],serviceWorkers:'allow'});owned=ownedProcesses(profile);
 report.owned=owned;const page=context.pages()[0];page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});await page.goto(report.url);await page.waitForSelector('.wait-compass');await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await page.waitForTimeout(1000);await page.screenshot({path:path.join(out,'reference-result-desktop.png'),fullPage:true});report.checks.push({name:'offline-shell-installed',passed:await page.evaluate(async()=>!!await caches.match('/codex/index.html'))});
 const initial=await page.evaluate(async()=>{const {read}=await import('./shared/storage.mjs');const s=await read();return {records:s.records.length,items:s.items.length}});assert.equal(initial.records,56);report.initial=initial;
 for(const [label,width,height]of [['desktop',1440,940],['tablet',820,1180],['portrait',390,844],['landscape',844,390]]){await page.setViewportSize({width,height});await page.screenshot({path:path.join(out,`${label}.png`),fullPage:true});const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,compass:!!document.querySelector('.wait-compass'),linear:!!document.querySelector('.wait-line'),minButton:Math.min(...[...document.querySelectorAll('button')].filter(e=>e.offsetHeight).map(e=>e.getBoundingClientRect().height))}));assert.equal(layout.overflow,false,label);assert.ok(layout.minButton>=44,label);report.checks.push({name:`layout-${label}`,passed:true,...layout})}
 await page.setViewportSize({width:1440,height:940});const saved=await page.evaluate(async()=>{const {mutate}=await import('./shared/storage.mjs');const at=new Date(Date.now()+3600000).toISOString();await mutate(s=>{s.plans.push({id:'qa-browser-exact',kind:'manual',title:'[QA] Isolated synthetic reset',at,url:null,snoozedUntil:new Date(Date.now()+1800000).toISOString(),snoozePending:true,repeatHours:2.5});return s});return at});await context.setOffline(true);await page.close();const cold=await context.newPage();await cold.goto(report.url);await cold.waitForSelector('[data-clock="seconds"]');assert.ok((await cold.textContent('.hero')).includes('[QA]'));const coldData=await cold.evaluate(async()=>{const {read}=await import('./shared/storage.mjs');const s=await read();return {plan:s.plans.find(p=>p.id==='qa-browser-exact'),records:s.records.length}});assert.equal(coldData.plan.at,saved);assert.equal(coldData.plan.repeatHours,2.5);assert.ok(coldData.plan.snoozedUntil);assert.equal(coldData.records,56);const before=await cold.textContent('[data-clock="seconds"]');await cold.waitForTimeout(1200);assert.notEqual(await cold.textContent('[data-clock="seconds"]'),before);await cold.screenshot({path:path.join(out,'cold-offline-countdown-qa.png'),fullPage:true});report.checks.push({name:'tab-close-cold-offline-deadline-snooze',passed:true});
 await context.setOffline(false);await cold.reload();await cold.waitForSelector('.wait-compass');await cold.goto(report.url+'#settings');await cold.waitForSelector('[data-action="enable-push"]');try{await cold.click('[data-action="enable-push"]');await waitFor(cold,async()=>{const {read}=await import('./shared/storage.mjs');return !!await read('device')},45000);await cold.click('[data-action="test-push"]');await waitFor(cold,async()=>{const {read}=await import('./shared/storage.mjs');return (await read()).journal.some(j=>j.kind==='push-received')},45000);const received=await cold.evaluate(async()=>{const {read}=await import('./shared/storage.mjs');const s=await read();return {pushReceived:s.journal.some(j=>j.kind==='push-received'),test:s.inbox.find(n=>n.id.startsWith('test:'))}});report.push=received;assert.ok(received.pushReceived,'Actual PushEvent receipt required');report.checks.push({name:'real-web-push-round-trip',passed:true});await cold.goto(report.url+'#inbox');await cold.screenshot({path:path.join(out,'real-push-inbox.png'),fullPage:true})}catch(e){process.exitCode=1;report.push={verified:false,error:e.message};report.checks.push({name:'real-web-push-round-trip',passed:false});await cold.screenshot({path:path.join(out,'push-setup-state.png'),fullPage:true})}
 const perf=await cold.evaluate(()=>new Promise(resolve=>{const samples=[],tasks=[],obs=new PerformanceObserver(list=>tasks.push(...list.getEntries().map(e=>e.duration)));obs.observe({type:'longtask',buffered:false});let last=performance.now();function frame(t){samples.push(t-last);last=t;if(samples.length<240)requestAnimationFrame(frame);else{obs.disconnect();samples.sort((a,b)=>a-b);resolve({frames:samples.length,p95:samples[Math.floor(samples.length*.95)],max:samples.at(-1),longTasks:tasks,heap:performance.memory?.usedJSHeapSize})}}requestAnimationFrame(frame)}));report.performance=perf;
}catch(e){report.fatal=e.stack;process.exitCode=1}finally{if(context){try{const p=context.pages()[0];if(p)await p.evaluate(async()=>{const {read,write}=await import('./shared/storage.mjs');const d=await read('device');if(d){await fetch('/api/subscribe',{method:'DELETE',headers:{Authorization:`Bearer ${d.token}`}});await (await navigator.serviceWorker.ready).pushManager.getSubscription().then(s=>s?.unsubscribe());await write('device',null)}})}catch{}await context.close();}const alive=processes().filter(p=>owned.some(x=>x.pid===p.ProcessId&&x.created===p.CreationDate));report.cleanup={remaining:alive.map(p=>p.ProcessId)};if(alive.length)process.exitCode=1;await fs.writeFile(path.join(out,'qa-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))}
